#!/usr/bin/env python

from sys import argv
from os import _exit
from subprocess import call
from os.path import join, dirname, realpath


path = join(dirname(realpath(__file__)), "git_hook.py")

argv.remove(__file__)
_exit(call([path, 'checkout'] + argv))
