#!/usr/bin/env python

from sys import argv
from os import _exit
from os.path import join, dirname, realpath
from subprocess import call


path = join(dirname(realpath(__file__)), "git_hook.py")

argv.remove(__file__)
_exit(call([path, 'merge'] + argv))
