#!/bin/bash
set -e

PACKAGE=sapo-pay-perl
DESCRIPTION="Sapo Pay Perl Runtime and Modules"
BASEDIR=/servers/pay

pre_build_hook() {
    echo
}

copy_content() {
    echo "Copying content to $1"
    mkdir -p $1/$BASEDIR/perl-5.38

    cp -a ./perl-5.38/* $1/$BASEDIR/perl-5.38
}

. ./tools/packager.sh

