#!/bin/bash
set -e

PACKAGE=sapo-pay-perl
DESCRIPTION="Sapo Pay Perl Runtime and Modules"
BASEDIR=/servers/pay/perl

pre_build_hook() {
    echo
}

copy_content() {
    echo "Copying content to $1"
    mkdir -p $1/$BASEDIR

    cp -a ./perl $1/$BASEDIR
}

. ./tools/packager.sh
